spring:
  application:
    name: iot-ble-server
  
  # データベース設定（H2インメモリデータベース）
  datasource:
    url: jdbc:h2:mem:locationdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2コンソール設定
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA設定
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # Thymeleaf設定
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# サーバー設定
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# ログ設定
logging:
  level:
    root: INFO
    com.example.iotble: DEBUG
    org.springframework.web: DEBUG
